/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "secondary-fixed-dim": "#adc6ff",
                "secondary-fixed": "#d8e2ff",
                "surface-container-low": "#f0f4fa",
                "surface-container-highest": "#dee3e8",
                "tertiary-fixed-dim": "#ffb691",
                "primary-fixed": "#d8e2ff",
                "on-secondary-fixed-variant": "#004494",
                "on-tertiary-container": "#0e0200",
                "tertiary-fixed": "#ffdbcb",
                "on-primary-fixed": "#001a41",
                "surface-container-high": "#e4e9ee",
                "on-background": "#171c20",
                "tertiary-container": "#c55500",
                "surface-bright": "#f6faff",
                "on-secondary": "#ffffff",
                "inverse-primary": "#adc7ff",
                "primary-fixed-dim": "#adc7ff",
                "primary": "#005bbf",
                "on-tertiary-fixed-variant": "#783100",
                "on-primary-fixed-variant": "#004493",
                "surface-tint": "#005bc0",
                "on-surface-variant": "#414754",
                "primary-container": "#1a73e8",
                "on-tertiary-fixed": "#341100",
                "outline": "#727785",
                "on-primary-container": "#ffffff",
                "on-secondary-fixed": "#001a41",
                "inverse-surface": "#2c3135",
                "on-error": "#ffffff",
                "surface": "#f6faff",
                "on-error-container": "#93000a",
                "inverse-on-surface": "#edf1f7",
                "background": "#f6faff",
                "on-primary": "#ffffff",
                "surface-container-lowest": "#ffffff",
                "tertiary": "#9e4300",
                "on-surface": "#171c20",
                "error": "#ba1a1a",
                "on-tertiary": "#ffffff",
                "outline-variant": "#c1c6d6",
                "surface-container": "#eaeef4",
                "secondary-container": "#4d8efe",
                "surface-variant": "#dee3e8",
                "error-container": "#ffdad6",
                "surface-dim": "#d6dae0",
                "on-secondary-container": "#00285c",
                "secondary": "#005ac1"
            },
            borderRadius: {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            spacing: {
                "unit": "8px",
                "margin-desktop": "48px",
                "margin-mobile": "16px",
                "stack-lg": "32px",
                "stack-md": "16px",
                "stack-sm": "8px",
                "gutter": "24px",
                "container-max-width": "1200px"
            },
            fontFamily: {
                "body-md": ["Inter"],
                "label-sm": ["Inter"],
                "headline-md": ["Manrope"],
                "display-lg": ["Manrope"],
                "body-lg": ["Inter"],
                "caption": ["Inter"]
            },
            fontSize: {
                "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
                "label-sm": ["14px", { lineHeight: "20px", fontWeight: "500" }],
                "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
                "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
                "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
                "caption": ["12px", { lineHeight: "16px", fontWeight: "400" }]
            }
        },
    },
    plugins: [],
}